/*Aqui é criada uma tabela contato e epecificado valores não nulos para 
  nao ficarem vazios, e para por padrão é utilizado o DEFAULT*/
CREATE TABLE contato
(
    ID INT PRIMARY KEY,
    NOME VARCHAR(30)    NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL DEFAULT 'Silva',
    NASCIMENTO DECIMAL(10,2)
);

/*anti duplicação*/

CREATE TABLE  EMAIL
(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    CONTATO_FK INT,
    FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);

/*CHAVE ESTRANGEIRA E REFERENCIAL*/

CREATE TABLE EMAIL
(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL,
    CONTATO_FK INT,
    FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO (ID)
);
CREATE TABLE TELEFONE
(
  ID INT PRIMARY KEY,
  TELEFONE VARCHAR(20) NOT NULL,
  CONTATO_FK INT,
  FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);

/*CONSULTAS BÁSICAS*/

SELECT  NOME TELEFONE
FROM    CONTATO, TELEDONE
WHERE   CONTATO.ID =  TELEFONE.CONTATO_FK AND CONTATO.SOBRENOME = 'SILVA';

///

SELECT  NOME, TELEFONE, EMAIL
FROM    CONTATO, TELEFONE, EMAIL
WHERE   CONTATO.ID = TELEFONE.CONTATO_FK AND CONTATO.ID = EMAIL.CONTATO_FK AND CONTATO.NOME = 'EDSON';

///

SELECT    TELEFONE.ID
FROM      CONTATO, TELEFONE
WHERE     TELEFONE.CONTATO_FK = CONTATO.ID
AND       CONTATO.PESO > 70;

/*COMANDO AS*/

SELECT    CONTATO.NOME AS N, GRUPO.NOME AS G
FROM      CONTATO, GRUPO, AFILIACAO
WHERE CONTATO.ID = AFILIACAO.CONTATO_FK AND GRUPO.ID = AFILICAO.GRUPO_FK AND N = 'JOAQUIM';

/**/

SELECT    C.PESO
FROM      CONTATO AS C
WHERE C.PESO < 100;

/*SELECIONAR TODA DT_NASC DE CONTATOS*/

SELECT NASCIMENTO
FROM   CONTATO;

/*SELECIONA TODOS OS ATRIBUTOS COM PESO 75*/

SELECT  *  
FROM    CONTATO
WHERE PESO = 75;

/*TODOS OS SOBRENOMES QUE NÃO SE REPETEM (DISTINTOS, DIFERENTES)DE CONTATOS*/

SELECT DISTINCT SOBRENOME
FROM            CONTATO;

/*TELEFONES QUE COMECEM COM 44*/

SELECT  *
FROM    TELEFONE
WHERE   TELEFONE LIKE '44%';

/*CONTATOS Q NASCERAM EM 1980*/

SELECT  *
FROM    CONTATO
WHERE NASCIMENTO LIKE '198_-__-__';

/*CONTATOS COM PESO ENTRE 90 E 100*/

SELECT  *
FROM    CONTATO
WHERE   PESO BETWEEN 90 AND 100;

/*NOMES EM ORDEM ALFABETICA*/

SELECT NOME
FROM CONTATO
ORDER BY NOME ASC;

/*SELECIONA NOME E SOBRENOME QUE COMECE COM A E ORDENA EM DECRESCENTE E CRESCENTE*/

SELECT  NOME, SOBRENOME
FROM    CONTATO
WHERE   SOBRENOME LIKA 'A%'
ORDER BY SOBRENOME DESC, NOME ASC;

/*comando insert NA ORDEM*/

INSERT INTO CONTATO 
VALUES      (10, 'EDSON', 'YANAGA','1978-04-12', 95);

/*comando insert definindo a ORDEM*/

INSERT INTO CONTATO (NOME,SOBRENOME, PESO NASCIMENTO, ID)
VALUES      ('EDSON','YANAGA', '1978-04-12, 95');

/*INSERINDO COM DADOS DE OUTRA TABELA*/

CREATE TABLE LISTA_DE_NOMES
(
  NOME VARCHAR(30),
  SOBRENOME VARCHAR(30)
);
INSERT TABLE LISTA_DE_NOMES (NOME, SOBRENOME)
SELECT NOME,SOBRENOME
FROM   CONTATO
WHERE NASCIMENTO > '1980-01-01';

/*COMANDO UPDATE*/

UPDATE CONTATO
SET    PESO = 99, NASCIMENTO = '1982-04-25'
WHERE  NOME = 'CARLOS';

/**/

UPDATE CONTATO
SET    PESO = PESO * 1.1;

/*VALOR NULO*/

UPDATE CONTATO
SET    NASCIMENTO = NULL;

/*COMANDO DELETE*/

DELETE FROM TELEFONE
WHERE ID = 5;

/*deleta tudo*/

DELETE FROM CONTATO;

/* NULO*/

SELECT *
FROM CONTATO
WHERE NASCIMENTO IS NULL;

SELECT *
FROM CONTATO 
WHERE NASCIMENTO IS NOT NULL;]
