/*Aqui é criada uma tabela contato e epecificado valores não nulos para 
  nao ficarem vazios, e para por padrão é utilizado o DEFAULT*/
CREATE TABLE contato
(
    ID INT PRIMARY KEY,
    NOME VARCHAR(30)    NOT NULL,
    SOBRENOME VARCHAR(30) NOT NULL DEFAULT 'Silva',
    NASCIMENTO DECIMAL(10,2)
);

/*anti duplicação*/

CREATE TABLE  EMAIL
(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    CONTATO_FK INT,
    FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);

/*CHAVE ESTRANGEIRA E REFERENCIAL*/

CREATE TABLE EMAIL
(
    ID INT PRIMARY KEY,
    EMAIL VARCHAR(60) NOT NULL,
    CONTATO_FK INT,
    FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO (ID)
);
CREATE TABLE TELEFONE
(
  ID INT PRIMARY KEY,
  TELEFONE VARCHAR(20) NOT NULL,
  CONTATO_FK INT,
  FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);