Banco de dados
CREATE TABLE contato
(
	id	INT PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	sobrenome VARCHAR(30) NOT NULL,
	nascimento DATE,
	peso DECIMAL(10,2)
);
CREATE TABLE email 
(
	ID INT PRIMARY KEY,
	EMAIL VARCHAR(60) NOT NULL,
	CONTATO_FK INT,
	FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);
CREATE TABLE TELEFONE
(
	ID PRIMARY KEY,
	TELEFONE VARCHAR(30) NOT NULL,
	CONTATO_FK INTFOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);
CREATE TABLE GRUPO
(
	ID INT PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL
);
CREATE TABLE AFILIACAO
(
	grupo_fk int not null,
	CONTATO_FK INT NOT NULL,
	PRIMARY KEY (GRUPO_FK) REFERENCES GRUPO (ID),
	FOREIGN KEY (CONTATO_FK) REFERENCES CONTATO(ID)
);
